project: 
  type: website
  output-dir: docs
  
website: 
  page-navigation: true
  title: "PIFSC PSD Density Surface Modeling" 
  site-url: https://pifsc-protected-species-division.github.io/density_surface_modeling/ 
  repo-url: https://github.com/pifsc-protected-species-division/density_surface_modeling
  repo-actions: [edit, issue]
  # favicon: images/favicon.ico  
  
  sidebar:
    background: "#D9E3E4"
    logo: img/noaa_fisheries.png
    # favicon: img/noaa_fisheries.png
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://www.fisheries.noaa.gov/pacific-islands/science-data/whale-and-dolphin-surveys-pacific-islands
        text: "NMFS PIFSC PSD CRP"
      - icon: github
        href: https://github.com/pifsc-protected-species-division/density_surface_modeling/
        text: "PIFSC-PSD DSM"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - href: content/intro.qmd
        text: Introduction
      - href: content/s1_construct_segs/index.qmd
        text: 1. Segmenting DAS Survey Data
      - href: content/s2_est_g0_esw/index.qmd
        text: 2. Estimate g(0) and ESW
      - href: content/s3_env_data/index.qmd
        text: 3. Dowload envrion. data
      - href: content/s4_fit_models/index.qmd
        text: 4. Fit DSM models
      - href: content/s5_prediction/index.qmd
        text: 5. Predict abundance for selected regions
      - href: content/s6_varprop/index.qmd
        text: 6. Assess uncertainty



format:
  html:
    theme: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
    code-copy: true
    code-overflow: wrap
    toc: true

filters:
  - include-files.lua
  - quarto

  
