project: 
  type: website
  output-dir: docs
  
website: 
  page-navigation: true
  title: "PIFSC PSD Density Surface Modeling" 
  site-url: https://pifsc-protected-species-division.github.io/density_surface_modeling/ 
  repo-url: https://github.com/pifsc-protected-species-division/density_surface_modeling
  repo-actions: [edit, issue]
  # favicon: images/favicon.ico  
  
  sidebar:
    background: "#D9E3E4"
    logo: img/noaa_fisheries.png
    # favicon: img/noaa_fisheries.png
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://www.fisheries.noaa.gov/pacific-islands/science-data/providing-science-protect-marine-species
        text: "NMFS PIFSC PSD"
      - icon: github
        href: https://github.com/pifsc-protected-species-division/density_surface_modeling/
        text: "PIFSC-PSD"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - href: content/about.qmd
        text: About
        

format:
  html:
    theme: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
    code-copy: true
    code-overflow: wrap
    toc: true

filters:
  - include-files.lua
  - quarto

  
